
spring:
#  cloud:
#    config:
#      #不启用config组件
#      enabled: false

  application:
    name: eureka-client-port1
eureka:
  client:
    serviceUrl:
      #将该服务注册到Eureka中进行管理
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/