server:
  port: 8081

spring:
#  cloud:
#    config:
#      #不启用config组件
#      enabled: false

  application:
    name: eureka-client-port1
eureka:
  client:
    #eureka控制台的刷新时间 默认30s
    instanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      #将该服务注册到Eureka中进行管理
      defaultZone: http://localhost:8761/eureka/