server:
  port: 8081

spring:
#  cloud:
#    config:
#      #不启用config组件
#      enabled: false

  application:
    name: eureka-client-port1
  
  #mq的消费组 类似于rabbit中的topic模式
  cloud:
    stream:
      bindings:
        myInput:
          #group1消费组只有一个消费者
          group: group1
eureka:
  client:
    serviceUrl:
      #将该服务注册到Eureka中进行管理
      defaultZone: http://localhost:8761/eureka/