server:
  port: 8761

#节点1
spring:
  application:
    name: eureka-service
  profiles: slave1

eureka:
  client:
    serviceUrl:
      defaultZone: http://slave1:8762/eureka

---
#搭建集群 使用defaultZone节点中的属性值做相互的注册

server:
  port: 8762

#节点2
spring:
  application:
    name: eureka-service
  profiles: slave2

eureka:
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka
